# Built with Jekyll 3.2.0

# Setup
title:               "corpusED"
tagline:             'Vol I: Selections from the Modern English Collection'
description:         'corpusED aims to bring you reading editions of well curated corpora on the internet based on Ed. The Modern English collection was originally edited by the former e-text center at the University of Virginia'
url:                 'http://johanngillium.github.io'
baseurl:             '/corpused'


# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.5

# Exclusions from the final site
exclude: [optional, vendor]


